services:
  postgres_con:
    image: postgres:17-bookworm
    container_name: postgres_con
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=taxi_data_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ingestion_net

  ingestion_con:
    build: .
    image: ingestion_script
    container_name: ingestion_con
    depends_on:
      - postgres_con
    networks:
      - ingestion_net
    stdin_open:
      true
    tty:
      true

  pgadmin_con:
    image: dpage/pgadmin4
    container_name: pgadmin_con
    ports:
      - 8085:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@user.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    networks:
      - ingestion_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_con

volumes:
  postgres_data:
  pgadmin_data:

networks:
  ingestion_net:
